#!/usr/bin/env python3
"""Generate qgl_stub.c from ref_gl/qgl.h: defines every qgl* function pointer and ora_qgl_init(), which
points all of them at a no-op except the extension entry points that must stay NULL (so ref_gl takes the
non-multitexture, non-paletted, no-point-parameter paths exactly like the WebGL port)."""
import re, sys
src = open(sys.argv[1], encoding='latin-1').read().replace('\r', '')
body = src.split('\n#ifdef _WIN32\n\nextern  int   ( WINAPI')[0]
keep_null = {'qglMTexCoord2fSGIS', 'qglSelectTextureSGIS', 'qglColorTableEXT', 'qglPointParameterfEXT',
             'qglPointParameterfvEXT', 'qglLockArraysEXT', 'qglUnlockArraysEXT'}
out = ['/* generated by gen_qgl_stub.py -- do not edit */', '#include "gl_local.h"', 'static void nop(void) {}']
names = []
for m in re.finditer(r'^extern\s+(.*?\(\s*APIENTRY\s*\*\s*(qgl\w+)\s*\).*?;)', body, re.M):
    out.append(m.group(1))
    names.append(m.group(2))
out.append('void ora_qgl_init(void) {')
for n in names:
    if n not in keep_null:
        out.append(f'  *(void **)&{n} = (void *)nop;')
out.append('}')
print('\n'.join(out))
