/* Generates src/generated/tables.ts from ref_gl/anormtab.h and ref_gl/warpsin.h (exact float32 values).
   cc -I../../../Quake-2/ref_gl scripts/gen_tables.c -o /tmp/gen && /tmp/gen > src/generated/tables.ts */
#include <stdio.h>
static float anormtab[16][256] =
#include "anormtab.h"
;
static float turbsin[] = {
#include "warpsin.h"
};
int main(void) {
  int i, j;
  printf("// Generated by scripts/gen_tables.c from ref_gl/anormtab.h and ref_gl/warpsin.h. Do not edit.\n\n");
  printf("/** C: ref_gl/gl_mesh.c r_avertexnormal_dots[SHADEDOT_QUANT][256] (anormtab.h), row-major. */\n");
  printf("export const R_AVERTEXNORMAL_DOTS: Float32Array = new Float32Array([\n");
  for (i = 0; i < 16; i++) {
    for (j = 0; j < 256; j++) printf("%s%.9g,", (j % 8) ? " " : "  ", anormtab[i][j]), (j % 8 == 7) && printf("\n");
  }
  printf("]);\n\n");
  printf("/** C: ref_gl/gl_warp.c r_turbsin[256] (warpsin.h) as initialised, before R_Init halves it. */\n");
  printf("export const R_TURBSIN_RAW: Float32Array = new Float32Array([\n");
  for (j = 0; j < (int)(sizeof(turbsin) / sizeof(turbsin[0])); j++) printf("%s%.9g,", (j % 8) ? " " : "  ", turbsin[j]), (j % 8 == 7) && printf("\n");
  printf("]);\n");
  return 0;
}
