// config.cfg text (CL_WriteConfiguration: `bind KEY "cmd"` + `set name "value"` lines) persisted per
// account through GET/PUT /api/v1/settings and mirrored to localStorage (used when offline / logged out).
import { api, ApiError } from './api';

const LS_KEY = 'q2.config.cfg';

export function readLocalConfig(): string | null {
  try {
    return localStorage.getItem(LS_KEY);
  } catch {
    return null;
  }
}

export function writeLocalConfig(text: string): void {
  try {
    localStorage.setItem(LS_KEY, text);
  } catch {
    // storage unavailable
  }
}

/** The user's config text: server copy when logged in (newer wins over nothing), else the local mirror. */
export async function loadConfigText(): Promise<string | undefined> {
  try {
    const s = await api.getSettings();
    if (s.config) {
      writeLocalConfig(s.config);
      return s.config;
    }
  } catch (e) {
    if (!(e instanceof ApiError) || e.status !== 401) console.warn('settings: using local copy', e);
  }
  return readLocalConfig() ?? undefined;
}

/** Saves locally and (best effort) to the account. Returns false if the server copy failed. */
export async function saveConfigText(text: string): Promise<boolean> {
  writeLocalConfig(text);
  try {
    await api.putSettings(text);
    return true;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------- parsing / editing

/** Minimal COM_Parse-style tokenizer for one config line (quoted strings, // comments). */
export function tokenizeLine(line: string): string[] {
  const out: string[] = [];
  let i = 0;
  while (i < line.length) {
    const ch = line[i]!;
    if (ch === ' ' || ch === '\t' || ch === '\r') {
      i++;
      continue;
    }
    if (ch === '/' && line[i + 1] === '/') break;
    if (ch === '"') {
      const end = line.indexOf('"', i + 1);
      out.push(line.slice(i + 1, end < 0 ? line.length : end));
      i = end < 0 ? line.length : end + 1;
      continue;
    }
    let j = i;
    while (j < line.length && line[j] !== ' ' && line[j] !== '\t' && line[j] !== '"') j++;
    out.push(line.slice(i, j));
    i = j;
  }
  return out;
}

export interface ParsedConfig {
  /** key name (keys.c spelling, e.g. "w", "MOUSE1", "UPARROW") → command */
  binds: Map<string, string>;
  cvars: Map<string, string>;
  /** unbindall seen: defaults from default.cfg do not apply */
  unbindall: boolean;
  /** lines that are neither bind nor set (aliases, exec, …) kept verbatim */
  other: string[];
}

/** Parses config text; later lines override earlier ones (like executing it). Commands split on ';'. */
export function parseConfig(text: string, into?: ParsedConfig): ParsedConfig {
  const cfg: ParsedConfig = into ?? { binds: new Map(), cvars: new Map(), unbindall: false, other: [] };
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('//')) continue;
    const t = tokenizeLine(line);
    const cmd = (t[0] ?? '').toLowerCase();
    if (cmd === 'bind' && t.length >= 2) {
      const key = normalizeKeyName(t[1]!);
      if (t.length >= 3) cfg.binds.set(key, t.slice(2).join(' '));
      else cfg.binds.delete(key);
    } else if (cmd === 'unbind' && t[1]) cfg.binds.delete(normalizeKeyName(t[1]));
    else if (cmd === 'unbindall') {
      cfg.binds.clear();
      cfg.unbindall = true;
    } else if ((cmd === 'set' || cmd === 'seta') && t.length >= 3) cfg.cvars.set(t[1]!, t[2]!);
    else cfg.other.push(line);
  }
  return cfg;
}

/** keys.c names are case-insensitive; single characters are stored lowercase. */
export function normalizeKeyName(k: string): string {
  return k.length === 1 ? k.toLowerCase() : k.toUpperCase();
}

function quote(s: string): string {
  return `"${s.replace(/"/g, "'")}"`;
}

/** Serializes back into CL_WriteConfiguration's shape. */
export function serializeConfig(cfg: ParsedConfig): string {
  let out = '// generated by quake, do not modify\n';
  if (cfg.unbindall) out += 'unbindall\n';
  for (const [k, v] of cfg.binds) out += `bind ${k} ${quote(v)}\n`;
  for (const [k, v] of cfg.cvars) out += `set ${k} ${quote(v)}\n`;
  for (const l of cfg.other) out += l + '\n';
  return out;
}
