// Code generated by genconst from the Quake-2 oracle headers. DO NOT EDIT.

// Package q2const holds constants shared by the Quake 2 engine, game and client.
package q2const

const (
	PITCH                            = 0                                // game/q_shared.h:64
	YAW                              = 1                                // game/q_shared.h:65
	ROLL                             = 2                                // game/q_shared.h:66
	MAX_STRING_CHARS                 = 1024                             // game/q_shared.h:68
	MAX_STRING_TOKENS                = 80                               // game/q_shared.h:69
	MAX_TOKEN_CHARS                  = 128                              // game/q_shared.h:70
	MAX_QPATH                        = 64                               // game/q_shared.h:72
	MAX_OSPATH                       = 128                              // game/q_shared.h:73
	MAX_CLIENTS                      = 256                              // game/q_shared.h:78
	MAX_EDICTS                       = 1024                             // game/q_shared.h:79
	MAX_LIGHTSTYLES                  = 256                              // game/q_shared.h:80
	MAX_MODELS                       = 256                              // game/q_shared.h:81
	MAX_SOUNDS                       = 256                              // game/q_shared.h:82
	MAX_IMAGES                       = 256                              // game/q_shared.h:83
	MAX_ITEMS                        = 256                              // game/q_shared.h:84
	MAX_GENERAL                      = 512                              // game/q_shared.h:85
	PRINT_LOW                        = 0                                // game/q_shared.h:89
	PRINT_MEDIUM                     = 1                                // game/q_shared.h:90
	PRINT_HIGH                       = 2                                // game/q_shared.h:91
	PRINT_CHAT                       = 3                                // game/q_shared.h:92
	ERR_FATAL                        = 0                                // game/q_shared.h:96
	ERR_DROP                         = 1                                // game/q_shared.h:97
	ERR_DISCONNECT                   = 2                                // game/q_shared.h:98
	PRINT_ALL                        = 0                                // game/q_shared.h:100
	PRINT_DEVELOPER                  = 1                                // game/q_shared.h:101
	PRINT_ALERT                      = 2                                // game/q_shared.h:102
	MULTICAST_ALL                    = 0                                // game/q_shared.h:114
	MULTICAST_PHS                    = 1                                // game/q_shared.h:114
	MULTICAST_PVS                    = 2                                // game/q_shared.h:114
	MULTICAST_ALL_R                  = 3                                // game/q_shared.h:114
	MULTICAST_PHS_R                  = 4                                // game/q_shared.h:114
	MULTICAST_PVS_R                  = 5                                // game/q_shared.h:114
	MAX_INFO_KEY                     = 64                               // game/q_shared.h:249
	MAX_INFO_VALUE                   = 64                               // game/q_shared.h:250
	MAX_INFO_STRING                  = 512                              // game/q_shared.h:251
	SFF_ARCH                         = 1                                // game/q_shared.h:278
	SFF_HIDDEN                       = 2                                // game/q_shared.h:279
	SFF_RDONLY                       = 4                                // game/q_shared.h:280
	SFF_SUBDIR                       = 8                                // game/q_shared.h:281
	SFF_SYSTEM                       = 16                               // game/q_shared.h:282
	CVAR_ARCHIVE                     = 1                                // game/q_shared.h:308
	CVAR_USERINFO                    = 2                                // game/q_shared.h:309
	CVAR_SERVERINFO                  = 4                                // game/q_shared.h:310
	CVAR_NOSET                       = 8                                // game/q_shared.h:311
	CVAR_LATCH                       = 16                               // game/q_shared.h:313
	CONTENTS_SOLID                   = 1                                // game/q_shared.h:338
	CONTENTS_WINDOW                  = 2                                // game/q_shared.h:339
	CONTENTS_AUX                     = 4                                // game/q_shared.h:340
	CONTENTS_LAVA                    = 8                                // game/q_shared.h:341
	CONTENTS_SLIME                   = 16                               // game/q_shared.h:342
	CONTENTS_WATER                   = 32                               // game/q_shared.h:343
	CONTENTS_MIST                    = 64                               // game/q_shared.h:344
	LAST_VISIBLE_CONTENTS            = 64                               // game/q_shared.h:345
	CONTENTS_AREAPORTAL              = 32768                            // game/q_shared.h:349
	CONTENTS_PLAYERCLIP              = 65536                            // game/q_shared.h:351
	CONTENTS_MONSTERCLIP             = 131072                           // game/q_shared.h:352
	CONTENTS_CURRENT_0               = 262144                           // game/q_shared.h:355
	CONTENTS_CURRENT_90              = 524288                           // game/q_shared.h:356
	CONTENTS_CURRENT_180             = 1048576                          // game/q_shared.h:357
	CONTENTS_CURRENT_270             = 2097152                          // game/q_shared.h:358
	CONTENTS_CURRENT_UP              = 4194304                          // game/q_shared.h:359
	CONTENTS_CURRENT_DOWN            = 8388608                          // game/q_shared.h:360
	CONTENTS_ORIGIN                  = 16777216                         // game/q_shared.h:362
	CONTENTS_MONSTER                 = 33554432                         // game/q_shared.h:364
	CONTENTS_DEADMONSTER             = 67108864                         // game/q_shared.h:365
	CONTENTS_DETAIL                  = 134217728                        // game/q_shared.h:366
	CONTENTS_TRANSLUCENT             = 268435456                        // game/q_shared.h:367
	CONTENTS_LADDER                  = 536870912                        // game/q_shared.h:368
	SURF_LIGHT                       = 1                                // game/q_shared.h:372
	SURF_SLICK                       = 2                                // game/q_shared.h:374
	SURF_SKY                         = 4                                // game/q_shared.h:376
	SURF_WARP                        = 8                                // game/q_shared.h:377
	SURF_TRANS33                     = 16                               // game/q_shared.h:378
	SURF_TRANS66                     = 32                               // game/q_shared.h:379
	SURF_FLOWING                     = 64                               // game/q_shared.h:380
	SURF_NODRAW                      = 128                              // game/q_shared.h:381
	MASK_ALL                         = -1                               // game/q_shared.h:386
	MASK_SOLID                       = 3                                // game/q_shared.h:387
	MASK_PLAYERSOLID                 = 33619971                         // game/q_shared.h:388
	MASK_DEADSOLID                   = 65539                            // game/q_shared.h:389
	MASK_MONSTERSOLID                = 33685507                         // game/q_shared.h:390
	MASK_WATER                       = 56                               // game/q_shared.h:391
	MASK_OPAQUE                      = 25                               // game/q_shared.h:392
	MASK_SHOT                        = 100663299                        // game/q_shared.h:393
	MASK_CURRENT                     = 16515072                         // game/q_shared.h:394
	AREA_SOLID                       = 1                                // game/q_shared.h:399
	AREA_TRIGGERS                    = 2                                // game/q_shared.h:400
	CPLANE_NORMAL_X                  = 0                                // game/q_shared.h:415
	CPLANE_NORMAL_Y                  = 4                                // game/q_shared.h:416
	CPLANE_NORMAL_Z                  = 8                                // game/q_shared.h:417
	CPLANE_DIST                      = 12                               // game/q_shared.h:418
	CPLANE_TYPE                      = 16                               // game/q_shared.h:419
	CPLANE_SIGNBITS                  = 17                               // game/q_shared.h:420
	CPLANE_PAD0                      = 18                               // game/q_shared.h:421
	CPLANE_PAD1                      = 19                               // game/q_shared.h:422
	PM_NORMAL                        = 0                                // game/q_shared.h:470
	PM_SPECTATOR                     = 1                                // game/q_shared.h:470
	PM_DEAD                          = 2                                // game/q_shared.h:470
	PM_GIB                           = 3                                // game/q_shared.h:470
	PM_FREEZE                        = 4                                // game/q_shared.h:470
	PMF_DUCKED                       = 1                                // game/q_shared.h:473
	PMF_JUMP_HELD                    = 2                                // game/q_shared.h:474
	PMF_ON_GROUND                    = 4                                // game/q_shared.h:475
	PMF_TIME_WATERJUMP               = 8                                // game/q_shared.h:476
	PMF_TIME_LAND                    = 16                               // game/q_shared.h:477
	PMF_TIME_TELEPORT                = 32                               // game/q_shared.h:478
	PMF_NO_PREDICTION                = 64                               // game/q_shared.h:479
	BUTTON_ATTACK                    = 1                                // game/q_shared.h:503
	BUTTON_USE                       = 2                                // game/q_shared.h:504
	BUTTON_ANY                       = 128                              // game/q_shared.h:505
	MAXTOUCH                         = 32                               // game/q_shared.h:520
	EF_ROTATE                        = 1                                // game/q_shared.h:554
	EF_GIB                           = 2                                // game/q_shared.h:555
	EF_BLASTER                       = 8                                // game/q_shared.h:556
	EF_ROCKET                        = 16                               // game/q_shared.h:557
	EF_GRENADE                       = 32                               // game/q_shared.h:558
	EF_HYPERBLASTER                  = 64                               // game/q_shared.h:559
	EF_BFG                           = 128                              // game/q_shared.h:560
	EF_COLOR_SHELL                   = 256                              // game/q_shared.h:561
	EF_POWERSCREEN                   = 512                              // game/q_shared.h:562
	EF_ANIM01                        = 1024                             // game/q_shared.h:563
	EF_ANIM23                        = 2048                             // game/q_shared.h:564
	EF_ANIM_ALL                      = 4096                             // game/q_shared.h:565
	EF_ANIM_ALLFAST                  = 8192                             // game/q_shared.h:566
	EF_FLIES                         = 16384                            // game/q_shared.h:567
	EF_QUAD                          = 32768                            // game/q_shared.h:568
	EF_PENT                          = 65536                            // game/q_shared.h:569
	EF_TELEPORTER                    = 131072                           // game/q_shared.h:570
	EF_FLAG1                         = 262144                           // game/q_shared.h:571
	EF_FLAG2                         = 524288                           // game/q_shared.h:572
	EF_IONRIPPER                     = 1048576                          // game/q_shared.h:574
	EF_GREENGIB                      = 2097152                          // game/q_shared.h:575
	EF_BLUEHYPERBLASTER              = 4194304                          // game/q_shared.h:576
	EF_SPINNINGLIGHTS                = 8388608                          // game/q_shared.h:577
	EF_PLASMA                        = 16777216                         // game/q_shared.h:578
	EF_TRAP                          = 33554432                         // game/q_shared.h:579
	EF_TRACKER                       = 67108864                         // game/q_shared.h:582
	EF_DOUBLE                        = 134217728                        // game/q_shared.h:583
	EF_SPHERETRANS                   = 268435456                        // game/q_shared.h:584
	EF_TAGTRAIL                      = 536870912                        // game/q_shared.h:585
	EF_HALF_DAMAGE                   = 1073741824                       // game/q_shared.h:586
	EF_TRACKERTRAIL                  = 2147483648                       // game/q_shared.h:587
	RF_MINLIGHT                      = 1                                // game/q_shared.h:591
	RF_VIEWERMODEL                   = 2                                // game/q_shared.h:592
	RF_WEAPONMODEL                   = 4                                // game/q_shared.h:593
	RF_FULLBRIGHT                    = 8                                // game/q_shared.h:594
	RF_DEPTHHACK                     = 16                               // game/q_shared.h:595
	RF_TRANSLUCENT                   = 32                               // game/q_shared.h:596
	RF_FRAMELERP                     = 64                               // game/q_shared.h:597
	RF_BEAM                          = 128                              // game/q_shared.h:598
	RF_CUSTOMSKIN                    = 256                              // game/q_shared.h:599
	RF_GLOW                          = 512                              // game/q_shared.h:600
	RF_SHELL_RED                     = 1024                             // game/q_shared.h:601
	RF_SHELL_GREEN                   = 2048                             // game/q_shared.h:602
	RF_SHELL_BLUE                    = 4096                             // game/q_shared.h:603
	RF_IR_VISIBLE                    = 32768                            // game/q_shared.h:606
	RF_SHELL_DOUBLE                  = 65536                            // game/q_shared.h:607
	RF_SHELL_HALF_DAM                = 131072                           // game/q_shared.h:608
	RF_USE_DISGUISE                  = 262144                           // game/q_shared.h:609
	RDF_UNDERWATER                   = 1                                // game/q_shared.h:613
	RDF_NOWORLDMODEL                 = 2                                // game/q_shared.h:614
	RDF_IRGOGGLES                    = 4                                // game/q_shared.h:617
	RDF_UVGOGGLES                    = 8                                // game/q_shared.h:618
	MZ_BLASTER                       = 0                                // game/q_shared.h:624
	MZ_MACHINEGUN                    = 1                                // game/q_shared.h:625
	MZ_SHOTGUN                       = 2                                // game/q_shared.h:626
	MZ_CHAINGUN1                     = 3                                // game/q_shared.h:627
	MZ_CHAINGUN2                     = 4                                // game/q_shared.h:628
	MZ_CHAINGUN3                     = 5                                // game/q_shared.h:629
	MZ_RAILGUN                       = 6                                // game/q_shared.h:630
	MZ_ROCKET                        = 7                                // game/q_shared.h:631
	MZ_GRENADE                       = 8                                // game/q_shared.h:632
	MZ_LOGIN                         = 9                                // game/q_shared.h:633
	MZ_LOGOUT                        = 10                               // game/q_shared.h:634
	MZ_RESPAWN                       = 11                               // game/q_shared.h:635
	MZ_BFG                           = 12                               // game/q_shared.h:636
	MZ_SSHOTGUN                      = 13                               // game/q_shared.h:637
	MZ_HYPERBLASTER                  = 14                               // game/q_shared.h:638
	MZ_ITEMRESPAWN                   = 15                               // game/q_shared.h:639
	MZ_IONRIPPER                     = 16                               // game/q_shared.h:641
	MZ_BLUEHYPERBLASTER              = 17                               // game/q_shared.h:642
	MZ_PHALANX                       = 18                               // game/q_shared.h:643
	MZ_SILENCED                      = 128                              // game/q_shared.h:644
	MZ_ETF_RIFLE                     = 30                               // game/q_shared.h:647
	MZ_UNUSED                        = 31                               // game/q_shared.h:648
	MZ_SHOTGUN2                      = 32                               // game/q_shared.h:649
	MZ_HEATBEAM                      = 33                               // game/q_shared.h:650
	MZ_BLASTER2                      = 34                               // game/q_shared.h:651
	MZ_TRACKER                       = 35                               // game/q_shared.h:652
	MZ_NUKE1                         = 36                               // game/q_shared.h:653
	MZ_NUKE2                         = 37                               // game/q_shared.h:654
	MZ_NUKE4                         = 38                               // game/q_shared.h:655
	MZ_NUKE8                         = 39                               // game/q_shared.h:656
	MZ2_TANK_BLASTER_1               = 1                                // game/q_shared.h:662
	MZ2_TANK_BLASTER_2               = 2                                // game/q_shared.h:663
	MZ2_TANK_BLASTER_3               = 3                                // game/q_shared.h:664
	MZ2_TANK_MACHINEGUN_1            = 4                                // game/q_shared.h:665
	MZ2_TANK_MACHINEGUN_2            = 5                                // game/q_shared.h:666
	MZ2_TANK_MACHINEGUN_3            = 6                                // game/q_shared.h:667
	MZ2_TANK_MACHINEGUN_4            = 7                                // game/q_shared.h:668
	MZ2_TANK_MACHINEGUN_5            = 8                                // game/q_shared.h:669
	MZ2_TANK_MACHINEGUN_6            = 9                                // game/q_shared.h:670
	MZ2_TANK_MACHINEGUN_7            = 10                               // game/q_shared.h:671
	MZ2_TANK_MACHINEGUN_8            = 11                               // game/q_shared.h:672
	MZ2_TANK_MACHINEGUN_9            = 12                               // game/q_shared.h:673
	MZ2_TANK_MACHINEGUN_10           = 13                               // game/q_shared.h:674
	MZ2_TANK_MACHINEGUN_11           = 14                               // game/q_shared.h:675
	MZ2_TANK_MACHINEGUN_12           = 15                               // game/q_shared.h:676
	MZ2_TANK_MACHINEGUN_13           = 16                               // game/q_shared.h:677
	MZ2_TANK_MACHINEGUN_14           = 17                               // game/q_shared.h:678
	MZ2_TANK_MACHINEGUN_15           = 18                               // game/q_shared.h:679
	MZ2_TANK_MACHINEGUN_16           = 19                               // game/q_shared.h:680
	MZ2_TANK_MACHINEGUN_17           = 20                               // game/q_shared.h:681
	MZ2_TANK_MACHINEGUN_18           = 21                               // game/q_shared.h:682
	MZ2_TANK_MACHINEGUN_19           = 22                               // game/q_shared.h:683
	MZ2_TANK_ROCKET_1                = 23                               // game/q_shared.h:684
	MZ2_TANK_ROCKET_2                = 24                               // game/q_shared.h:685
	MZ2_TANK_ROCKET_3                = 25                               // game/q_shared.h:686
	MZ2_INFANTRY_MACHINEGUN_1        = 26                               // game/q_shared.h:688
	MZ2_INFANTRY_MACHINEGUN_2        = 27                               // game/q_shared.h:689
	MZ2_INFANTRY_MACHINEGUN_3        = 28                               // game/q_shared.h:690
	MZ2_INFANTRY_MACHINEGUN_4        = 29                               // game/q_shared.h:691
	MZ2_INFANTRY_MACHINEGUN_5        = 30                               // game/q_shared.h:692
	MZ2_INFANTRY_MACHINEGUN_6        = 31                               // game/q_shared.h:693
	MZ2_INFANTRY_MACHINEGUN_7        = 32                               // game/q_shared.h:694
	MZ2_INFANTRY_MACHINEGUN_8        = 33                               // game/q_shared.h:695
	MZ2_INFANTRY_MACHINEGUN_9        = 34                               // game/q_shared.h:696
	MZ2_INFANTRY_MACHINEGUN_10       = 35                               // game/q_shared.h:697
	MZ2_INFANTRY_MACHINEGUN_11       = 36                               // game/q_shared.h:698
	MZ2_INFANTRY_MACHINEGUN_12       = 37                               // game/q_shared.h:699
	MZ2_INFANTRY_MACHINEGUN_13       = 38                               // game/q_shared.h:700
	MZ2_SOLDIER_BLASTER_1            = 39                               // game/q_shared.h:702
	MZ2_SOLDIER_BLASTER_2            = 40                               // game/q_shared.h:703
	MZ2_SOLDIER_SHOTGUN_1            = 41                               // game/q_shared.h:704
	MZ2_SOLDIER_SHOTGUN_2            = 42                               // game/q_shared.h:705
	MZ2_SOLDIER_MACHINEGUN_1         = 43                               // game/q_shared.h:706
	MZ2_SOLDIER_MACHINEGUN_2         = 44                               // game/q_shared.h:707
	MZ2_GUNNER_MACHINEGUN_1          = 45                               // game/q_shared.h:709
	MZ2_GUNNER_MACHINEGUN_2          = 46                               // game/q_shared.h:710
	MZ2_GUNNER_MACHINEGUN_3          = 47                               // game/q_shared.h:711
	MZ2_GUNNER_MACHINEGUN_4          = 48                               // game/q_shared.h:712
	MZ2_GUNNER_MACHINEGUN_5          = 49                               // game/q_shared.h:713
	MZ2_GUNNER_MACHINEGUN_6          = 50                               // game/q_shared.h:714
	MZ2_GUNNER_MACHINEGUN_7          = 51                               // game/q_shared.h:715
	MZ2_GUNNER_MACHINEGUN_8          = 52                               // game/q_shared.h:716
	MZ2_GUNNER_GRENADE_1             = 53                               // game/q_shared.h:717
	MZ2_GUNNER_GRENADE_2             = 54                               // game/q_shared.h:718
	MZ2_GUNNER_GRENADE_3             = 55                               // game/q_shared.h:719
	MZ2_GUNNER_GRENADE_4             = 56                               // game/q_shared.h:720
	MZ2_CHICK_ROCKET_1               = 57                               // game/q_shared.h:722
	MZ2_FLYER_BLASTER_1              = 58                               // game/q_shared.h:724
	MZ2_FLYER_BLASTER_2              = 59                               // game/q_shared.h:725
	MZ2_MEDIC_BLASTER_1              = 60                               // game/q_shared.h:727
	MZ2_GLADIATOR_RAILGUN_1          = 61                               // game/q_shared.h:729
	MZ2_HOVER_BLASTER_1              = 62                               // game/q_shared.h:731
	MZ2_ACTOR_MACHINEGUN_1           = 63                               // game/q_shared.h:733
	MZ2_SUPERTANK_MACHINEGUN_1       = 64                               // game/q_shared.h:735
	MZ2_SUPERTANK_MACHINEGUN_2       = 65                               // game/q_shared.h:736
	MZ2_SUPERTANK_MACHINEGUN_3       = 66                               // game/q_shared.h:737
	MZ2_SUPERTANK_MACHINEGUN_4       = 67                               // game/q_shared.h:738
	MZ2_SUPERTANK_MACHINEGUN_5       = 68                               // game/q_shared.h:739
	MZ2_SUPERTANK_MACHINEGUN_6       = 69                               // game/q_shared.h:740
	MZ2_SUPERTANK_ROCKET_1           = 70                               // game/q_shared.h:741
	MZ2_SUPERTANK_ROCKET_2           = 71                               // game/q_shared.h:742
	MZ2_SUPERTANK_ROCKET_3           = 72                               // game/q_shared.h:743
	MZ2_BOSS2_MACHINEGUN_L1          = 73                               // game/q_shared.h:745
	MZ2_BOSS2_MACHINEGUN_L2          = 74                               // game/q_shared.h:746
	MZ2_BOSS2_MACHINEGUN_L3          = 75                               // game/q_shared.h:747
	MZ2_BOSS2_MACHINEGUN_L4          = 76                               // game/q_shared.h:748
	MZ2_BOSS2_MACHINEGUN_L5          = 77                               // game/q_shared.h:749
	MZ2_BOSS2_ROCKET_1               = 78                               // game/q_shared.h:750
	MZ2_BOSS2_ROCKET_2               = 79                               // game/q_shared.h:751
	MZ2_BOSS2_ROCKET_3               = 80                               // game/q_shared.h:752
	MZ2_BOSS2_ROCKET_4               = 81                               // game/q_shared.h:753
	MZ2_FLOAT_BLASTER_1              = 82                               // game/q_shared.h:755
	MZ2_SOLDIER_BLASTER_3            = 83                               // game/q_shared.h:757
	MZ2_SOLDIER_SHOTGUN_3            = 84                               // game/q_shared.h:758
	MZ2_SOLDIER_MACHINEGUN_3         = 85                               // game/q_shared.h:759
	MZ2_SOLDIER_BLASTER_4            = 86                               // game/q_shared.h:760
	MZ2_SOLDIER_SHOTGUN_4            = 87                               // game/q_shared.h:761
	MZ2_SOLDIER_MACHINEGUN_4         = 88                               // game/q_shared.h:762
	MZ2_SOLDIER_BLASTER_5            = 89                               // game/q_shared.h:763
	MZ2_SOLDIER_SHOTGUN_5            = 90                               // game/q_shared.h:764
	MZ2_SOLDIER_MACHINEGUN_5         = 91                               // game/q_shared.h:765
	MZ2_SOLDIER_BLASTER_6            = 92                               // game/q_shared.h:766
	MZ2_SOLDIER_SHOTGUN_6            = 93                               // game/q_shared.h:767
	MZ2_SOLDIER_MACHINEGUN_6         = 94                               // game/q_shared.h:768
	MZ2_SOLDIER_BLASTER_7            = 95                               // game/q_shared.h:769
	MZ2_SOLDIER_SHOTGUN_7            = 96                               // game/q_shared.h:770
	MZ2_SOLDIER_MACHINEGUN_7         = 97                               // game/q_shared.h:771
	MZ2_SOLDIER_BLASTER_8            = 98                               // game/q_shared.h:772
	MZ2_SOLDIER_SHOTGUN_8            = 99                               // game/q_shared.h:773
	MZ2_SOLDIER_MACHINEGUN_8         = 100                              // game/q_shared.h:774
	MZ2_MAKRON_BFG                   = 101                              // game/q_shared.h:777
	MZ2_MAKRON_BLASTER_1             = 102                              // game/q_shared.h:778
	MZ2_MAKRON_BLASTER_2             = 103                              // game/q_shared.h:779
	MZ2_MAKRON_BLASTER_3             = 104                              // game/q_shared.h:780
	MZ2_MAKRON_BLASTER_4             = 105                              // game/q_shared.h:781
	MZ2_MAKRON_BLASTER_5             = 106                              // game/q_shared.h:782
	MZ2_MAKRON_BLASTER_6             = 107                              // game/q_shared.h:783
	MZ2_MAKRON_BLASTER_7             = 108                              // game/q_shared.h:784
	MZ2_MAKRON_BLASTER_8             = 109                              // game/q_shared.h:785
	MZ2_MAKRON_BLASTER_9             = 110                              // game/q_shared.h:786
	MZ2_MAKRON_BLASTER_10            = 111                              // game/q_shared.h:787
	MZ2_MAKRON_BLASTER_11            = 112                              // game/q_shared.h:788
	MZ2_MAKRON_BLASTER_12            = 113                              // game/q_shared.h:789
	MZ2_MAKRON_BLASTER_13            = 114                              // game/q_shared.h:790
	MZ2_MAKRON_BLASTER_14            = 115                              // game/q_shared.h:791
	MZ2_MAKRON_BLASTER_15            = 116                              // game/q_shared.h:792
	MZ2_MAKRON_BLASTER_16            = 117                              // game/q_shared.h:793
	MZ2_MAKRON_BLASTER_17            = 118                              // game/q_shared.h:794
	MZ2_MAKRON_RAILGUN_1             = 119                              // game/q_shared.h:795
	MZ2_JORG_MACHINEGUN_L1           = 120                              // game/q_shared.h:796
	MZ2_JORG_MACHINEGUN_L2           = 121                              // game/q_shared.h:797
	MZ2_JORG_MACHINEGUN_L3           = 122                              // game/q_shared.h:798
	MZ2_JORG_MACHINEGUN_L4           = 123                              // game/q_shared.h:799
	MZ2_JORG_MACHINEGUN_L5           = 124                              // game/q_shared.h:800
	MZ2_JORG_MACHINEGUN_L6           = 125                              // game/q_shared.h:801
	MZ2_JORG_MACHINEGUN_R1           = 126                              // game/q_shared.h:802
	MZ2_JORG_MACHINEGUN_R2           = 127                              // game/q_shared.h:803
	MZ2_JORG_MACHINEGUN_R3           = 128                              // game/q_shared.h:804
	MZ2_JORG_MACHINEGUN_R4           = 129                              // game/q_shared.h:805
	MZ2_JORG_MACHINEGUN_R5           = 130                              // game/q_shared.h:806
	MZ2_JORG_MACHINEGUN_R6           = 131                              // game/q_shared.h:807
	MZ2_JORG_BFG_1                   = 132                              // game/q_shared.h:808
	MZ2_BOSS2_MACHINEGUN_R1          = 133                              // game/q_shared.h:809
	MZ2_BOSS2_MACHINEGUN_R2          = 134                              // game/q_shared.h:810
	MZ2_BOSS2_MACHINEGUN_R3          = 135                              // game/q_shared.h:811
	MZ2_BOSS2_MACHINEGUN_R4          = 136                              // game/q_shared.h:812
	MZ2_BOSS2_MACHINEGUN_R5          = 137                              // game/q_shared.h:813
	MZ2_CARRIER_MACHINEGUN_L1        = 138                              // game/q_shared.h:816
	MZ2_CARRIER_MACHINEGUN_R1        = 139                              // game/q_shared.h:817
	MZ2_CARRIER_GRENADE              = 140                              // game/q_shared.h:818
	MZ2_TURRET_MACHINEGUN            = 141                              // game/q_shared.h:819
	MZ2_TURRET_ROCKET                = 142                              // game/q_shared.h:820
	MZ2_TURRET_BLASTER               = 143                              // game/q_shared.h:821
	MZ2_STALKER_BLASTER              = 144                              // game/q_shared.h:822
	MZ2_DAEDALUS_BLASTER             = 145                              // game/q_shared.h:823
	MZ2_MEDIC_BLASTER_2              = 146                              // game/q_shared.h:824
	MZ2_CARRIER_RAILGUN              = 147                              // game/q_shared.h:825
	MZ2_WIDOW_DISRUPTOR              = 148                              // game/q_shared.h:826
	MZ2_WIDOW_BLASTER                = 149                              // game/q_shared.h:827
	MZ2_WIDOW_RAIL                   = 150                              // game/q_shared.h:828
	MZ2_WIDOW_PLASMABEAM             = 151                              // game/q_shared.h:829
	MZ2_CARRIER_MACHINEGUN_L2        = 152                              // game/q_shared.h:830
	MZ2_CARRIER_MACHINEGUN_R2        = 153                              // game/q_shared.h:831
	MZ2_WIDOW_RAIL_LEFT              = 154                              // game/q_shared.h:832
	MZ2_WIDOW_RAIL_RIGHT             = 155                              // game/q_shared.h:833
	MZ2_WIDOW_BLASTER_SWEEP1         = 156                              // game/q_shared.h:834
	MZ2_WIDOW_BLASTER_SWEEP2         = 157                              // game/q_shared.h:835
	MZ2_WIDOW_BLASTER_SWEEP3         = 158                              // game/q_shared.h:836
	MZ2_WIDOW_BLASTER_SWEEP4         = 159                              // game/q_shared.h:837
	MZ2_WIDOW_BLASTER_SWEEP5         = 160                              // game/q_shared.h:838
	MZ2_WIDOW_BLASTER_SWEEP6         = 161                              // game/q_shared.h:839
	MZ2_WIDOW_BLASTER_SWEEP7         = 162                              // game/q_shared.h:840
	MZ2_WIDOW_BLASTER_SWEEP8         = 163                              // game/q_shared.h:841
	MZ2_WIDOW_BLASTER_SWEEP9         = 164                              // game/q_shared.h:842
	MZ2_WIDOW_BLASTER_100            = 165                              // game/q_shared.h:843
	MZ2_WIDOW_BLASTER_90             = 166                              // game/q_shared.h:844
	MZ2_WIDOW_BLASTER_80             = 167                              // game/q_shared.h:845
	MZ2_WIDOW_BLASTER_70             = 168                              // game/q_shared.h:846
	MZ2_WIDOW_BLASTER_60             = 169                              // game/q_shared.h:847
	MZ2_WIDOW_BLASTER_50             = 170                              // game/q_shared.h:848
	MZ2_WIDOW_BLASTER_40             = 171                              // game/q_shared.h:849
	MZ2_WIDOW_BLASTER_30             = 172                              // game/q_shared.h:850
	MZ2_WIDOW_BLASTER_20             = 173                              // game/q_shared.h:851
	MZ2_WIDOW_BLASTER_10             = 174                              // game/q_shared.h:852
	MZ2_WIDOW_BLASTER_0              = 175                              // game/q_shared.h:853
	MZ2_WIDOW_BLASTER_10L            = 176                              // game/q_shared.h:854
	MZ2_WIDOW_BLASTER_20L            = 177                              // game/q_shared.h:855
	MZ2_WIDOW_BLASTER_30L            = 178                              // game/q_shared.h:856
	MZ2_WIDOW_BLASTER_40L            = 179                              // game/q_shared.h:857
	MZ2_WIDOW_BLASTER_50L            = 180                              // game/q_shared.h:858
	MZ2_WIDOW_BLASTER_60L            = 181                              // game/q_shared.h:859
	MZ2_WIDOW_BLASTER_70L            = 182                              // game/q_shared.h:860
	MZ2_WIDOW_RUN_1                  = 183                              // game/q_shared.h:861
	MZ2_WIDOW_RUN_2                  = 184                              // game/q_shared.h:862
	MZ2_WIDOW_RUN_3                  = 185                              // game/q_shared.h:863
	MZ2_WIDOW_RUN_4                  = 186                              // game/q_shared.h:864
	MZ2_WIDOW_RUN_5                  = 187                              // game/q_shared.h:865
	MZ2_WIDOW_RUN_6                  = 188                              // game/q_shared.h:866
	MZ2_WIDOW_RUN_7                  = 189                              // game/q_shared.h:867
	MZ2_WIDOW_RUN_8                  = 190                              // game/q_shared.h:868
	MZ2_CARRIER_ROCKET_1             = 191                              // game/q_shared.h:869
	MZ2_CARRIER_ROCKET_2             = 192                              // game/q_shared.h:870
	MZ2_CARRIER_ROCKET_3             = 193                              // game/q_shared.h:871
	MZ2_CARRIER_ROCKET_4             = 194                              // game/q_shared.h:872
	MZ2_WIDOW2_BEAMER_1              = 195                              // game/q_shared.h:873
	MZ2_WIDOW2_BEAMER_2              = 196                              // game/q_shared.h:874
	MZ2_WIDOW2_BEAMER_3              = 197                              // game/q_shared.h:875
	MZ2_WIDOW2_BEAMER_4              = 198                              // game/q_shared.h:876
	MZ2_WIDOW2_BEAMER_5              = 199                              // game/q_shared.h:877
	MZ2_WIDOW2_BEAM_SWEEP_1          = 200                              // game/q_shared.h:878
	MZ2_WIDOW2_BEAM_SWEEP_2          = 201                              // game/q_shared.h:879
	MZ2_WIDOW2_BEAM_SWEEP_3          = 202                              // game/q_shared.h:880
	MZ2_WIDOW2_BEAM_SWEEP_4          = 203                              // game/q_shared.h:881
	MZ2_WIDOW2_BEAM_SWEEP_5          = 204                              // game/q_shared.h:882
	MZ2_WIDOW2_BEAM_SWEEP_6          = 205                              // game/q_shared.h:883
	MZ2_WIDOW2_BEAM_SWEEP_7          = 206                              // game/q_shared.h:884
	MZ2_WIDOW2_BEAM_SWEEP_8          = 207                              // game/q_shared.h:885
	MZ2_WIDOW2_BEAM_SWEEP_9          = 208                              // game/q_shared.h:886
	MZ2_WIDOW2_BEAM_SWEEP_10         = 209                              // game/q_shared.h:887
	MZ2_WIDOW2_BEAM_SWEEP_11         = 210                              // game/q_shared.h:888
	TE_GUNSHOT                       = 0                                // game/q_shared.h:961
	TE_BLOOD                         = 1                                // game/q_shared.h:961
	TE_BLASTER                       = 2                                // game/q_shared.h:961
	TE_RAILTRAIL                     = 3                                // game/q_shared.h:961
	TE_SHOTGUN                       = 4                                // game/q_shared.h:961
	TE_EXPLOSION1                    = 5                                // game/q_shared.h:961
	TE_EXPLOSION2                    = 6                                // game/q_shared.h:961
	TE_ROCKET_EXPLOSION              = 7                                // game/q_shared.h:961
	TE_GRENADE_EXPLOSION             = 8                                // game/q_shared.h:961
	TE_SPARKS                        = 9                                // game/q_shared.h:961
	TE_SPLASH                        = 10                               // game/q_shared.h:961
	TE_BUBBLETRAIL                   = 11                               // game/q_shared.h:961
	TE_SCREEN_SPARKS                 = 12                               // game/q_shared.h:961
	TE_SHIELD_SPARKS                 = 13                               // game/q_shared.h:961
	TE_BULLET_SPARKS                 = 14                               // game/q_shared.h:961
	TE_LASER_SPARKS                  = 15                               // game/q_shared.h:961
	TE_PARASITE_ATTACK               = 16                               // game/q_shared.h:961
	TE_ROCKET_EXPLOSION_WATER        = 17                               // game/q_shared.h:961
	TE_GRENADE_EXPLOSION_WATER       = 18                               // game/q_shared.h:961
	TE_MEDIC_CABLE_ATTACK            = 19                               // game/q_shared.h:961
	TE_BFG_EXPLOSION                 = 20                               // game/q_shared.h:961
	TE_BFG_BIGEXPLOSION              = 21                               // game/q_shared.h:961
	TE_BOSSTPORT                     = 22                               // game/q_shared.h:961
	TE_BFG_LASER                     = 23                               // game/q_shared.h:961
	TE_GRAPPLE_CABLE                 = 24                               // game/q_shared.h:961
	TE_WELDING_SPARKS                = 25                               // game/q_shared.h:961
	TE_GREENBLOOD                    = 26                               // game/q_shared.h:961
	TE_BLUEHYPERBLASTER              = 27                               // game/q_shared.h:961
	TE_PLASMA_EXPLOSION              = 28                               // game/q_shared.h:961
	TE_TUNNEL_SPARKS                 = 29                               // game/q_shared.h:961
	TE_BLASTER2                      = 30                               // game/q_shared.h:961
	TE_RAILTRAIL2                    = 31                               // game/q_shared.h:961
	TE_FLAME                         = 32                               // game/q_shared.h:961
	TE_LIGHTNING                     = 33                               // game/q_shared.h:961
	TE_DEBUGTRAIL                    = 34                               // game/q_shared.h:961
	TE_PLAIN_EXPLOSION               = 35                               // game/q_shared.h:961
	TE_FLASHLIGHT                    = 36                               // game/q_shared.h:961
	TE_FORCEWALL                     = 37                               // game/q_shared.h:961
	TE_HEATBEAM                      = 38                               // game/q_shared.h:961
	TE_MONSTER_HEATBEAM              = 39                               // game/q_shared.h:961
	TE_STEAM                         = 40                               // game/q_shared.h:961
	TE_BUBBLETRAIL2                  = 41                               // game/q_shared.h:961
	TE_MOREBLOOD                     = 42                               // game/q_shared.h:961
	TE_HEATBEAM_SPARKS               = 43                               // game/q_shared.h:961
	TE_HEATBEAM_STEAM                = 44                               // game/q_shared.h:961
	TE_CHAINFIST_SMOKE               = 45                               // game/q_shared.h:961
	TE_ELECTRIC_SPARKS               = 46                               // game/q_shared.h:961
	TE_TRACKER_EXPLOSION             = 47                               // game/q_shared.h:961
	TE_TELEPORT_EFFECT               = 48                               // game/q_shared.h:961
	TE_DBALL_GOAL                    = 49                               // game/q_shared.h:961
	TE_WIDOWBEAMOUT                  = 50                               // game/q_shared.h:961
	TE_NUKEBLAST                     = 51                               // game/q_shared.h:961
	TE_WIDOWSPLASH                   = 52                               // game/q_shared.h:961
	TE_EXPLOSION1_BIG                = 53                               // game/q_shared.h:961
	TE_EXPLOSION1_NP                 = 54                               // game/q_shared.h:961
	TE_FLECHETTE                     = 55                               // game/q_shared.h:961
	SPLASH_UNKNOWN                   = 0                                // game/q_shared.h:963
	SPLASH_SPARKS                    = 1                                // game/q_shared.h:964
	SPLASH_BLUE_WATER                = 2                                // game/q_shared.h:965
	SPLASH_BROWN_WATER               = 3                                // game/q_shared.h:966
	SPLASH_SLIME                     = 4                                // game/q_shared.h:967
	SPLASH_LAVA                      = 5                                // game/q_shared.h:968
	SPLASH_BLOOD                     = 6                                // game/q_shared.h:969
	CHAN_AUTO                        = 0                                // game/q_shared.h:975
	CHAN_WEAPON                      = 1                                // game/q_shared.h:976
	CHAN_VOICE                       = 2                                // game/q_shared.h:977
	CHAN_ITEM                        = 3                                // game/q_shared.h:978
	CHAN_BODY                        = 4                                // game/q_shared.h:979
	CHAN_NO_PHS_ADD                  = 8                                // game/q_shared.h:981
	CHAN_RELIABLE                    = 16                               // game/q_shared.h:982
	ATTN_NONE                        = 0                                // game/q_shared.h:986
	ATTN_NORM                        = 1                                // game/q_shared.h:987
	ATTN_IDLE                        = 2                                // game/q_shared.h:988
	ATTN_STATIC                      = 3                                // game/q_shared.h:989
	STAT_HEALTH_ICON                 = 0                                // game/q_shared.h:993
	STAT_HEALTH                      = 1                                // game/q_shared.h:994
	STAT_AMMO_ICON                   = 2                                // game/q_shared.h:995
	STAT_AMMO                        = 3                                // game/q_shared.h:996
	STAT_ARMOR_ICON                  = 4                                // game/q_shared.h:997
	STAT_ARMOR                       = 5                                // game/q_shared.h:998
	STAT_SELECTED_ICON               = 6                                // game/q_shared.h:999
	STAT_PICKUP_ICON                 = 7                                // game/q_shared.h:1000
	STAT_PICKUP_STRING               = 8                                // game/q_shared.h:1001
	STAT_TIMER_ICON                  = 9                                // game/q_shared.h:1002
	STAT_TIMER                       = 10                               // game/q_shared.h:1003
	STAT_HELPICON                    = 11                               // game/q_shared.h:1004
	STAT_SELECTED_ITEM               = 12                               // game/q_shared.h:1005
	STAT_LAYOUTS                     = 13                               // game/q_shared.h:1006
	STAT_FRAGS                       = 14                               // game/q_shared.h:1007
	STAT_FLASHES                     = 15                               // game/q_shared.h:1008
	STAT_CHASE                       = 16                               // game/q_shared.h:1009
	STAT_SPECTATOR                   = 17                               // game/q_shared.h:1010
	MAX_STATS                        = 32                               // game/q_shared.h:1012
	DF_NO_HEALTH                     = 1                                // game/q_shared.h:1016
	DF_NO_ITEMS                      = 2                                // game/q_shared.h:1017
	DF_WEAPONS_STAY                  = 4                                // game/q_shared.h:1018
	DF_NO_FALLING                    = 8                                // game/q_shared.h:1019
	DF_INSTANT_ITEMS                 = 16                               // game/q_shared.h:1020
	DF_SAME_LEVEL                    = 32                               // game/q_shared.h:1021
	DF_SKINTEAMS                     = 64                               // game/q_shared.h:1022
	DF_MODELTEAMS                    = 128                              // game/q_shared.h:1023
	DF_NO_FRIENDLY_FIRE              = 256                              // game/q_shared.h:1024
	DF_SPAWN_FARTHEST                = 512                              // game/q_shared.h:1025
	DF_FORCE_RESPAWN                 = 1024                             // game/q_shared.h:1026
	DF_NO_ARMOR                      = 2048                             // game/q_shared.h:1027
	DF_ALLOW_EXIT                    = 4096                             // game/q_shared.h:1028
	DF_INFINITE_AMMO                 = 8192                             // game/q_shared.h:1029
	DF_QUAD_DROP                     = 16384                            // game/q_shared.h:1030
	DF_FIXED_FOV                     = 32768                            // game/q_shared.h:1031
	DF_QUADFIRE_DROP                 = 65536                            // game/q_shared.h:1034
	DF_NO_MINES                      = 131072                           // game/q_shared.h:1037
	DF_NO_STACK_DOUBLE               = 262144                           // game/q_shared.h:1038
	DF_NO_NUKES                      = 524288                           // game/q_shared.h:1039
	DF_NO_SPHERES                    = 1048576                          // game/q_shared.h:1040
	ROGUE_VERSION_ID                 = 1278                             // game/q_shared.h:1071
	ROGUE_VERSION_STRING             = "08/21/1998 Beta 2 for Ensemble" // game/q_shared.h:1073
	CS_NAME                          = 0                                // game/q_shared.h:1093
	CS_CDTRACK                       = 1                                // game/q_shared.h:1094
	CS_SKY                           = 2                                // game/q_shared.h:1095
	CS_SKYAXIS                       = 3                                // game/q_shared.h:1096
	CS_SKYROTATE                     = 4                                // game/q_shared.h:1097
	CS_STATUSBAR                     = 5                                // game/q_shared.h:1098
	CS_AIRACCEL                      = 29                               // game/q_shared.h:1100
	CS_MAXCLIENTS                    = 30                               // game/q_shared.h:1101
	CS_MAPCHECKSUM                   = 31                               // game/q_shared.h:1102
	CS_MODELS                        = 32                               // game/q_shared.h:1104
	CS_SOUNDS                        = 288                              // game/q_shared.h:1105
	CS_IMAGES                        = 544                              // game/q_shared.h:1106
	CS_LIGHTS                        = 800                              // game/q_shared.h:1107
	CS_ITEMS                         = 1056                             // game/q_shared.h:1108
	CS_PLAYERSKINS                   = 1312                             // game/q_shared.h:1109
	CS_GENERAL                       = 1568                             // game/q_shared.h:1110
	MAX_CONFIGSTRINGS                = 2080                             // game/q_shared.h:1111
	EV_NONE                          = 0                                // game/q_shared.h:1131
	EV_ITEM_RESPAWN                  = 1                                // game/q_shared.h:1131
	EV_FOOTSTEP                      = 2                                // game/q_shared.h:1131
	EV_FALLSHORT                     = 3                                // game/q_shared.h:1131
	EV_FALL                          = 4                                // game/q_shared.h:1131
	EV_FALLFAR                       = 5                                // game/q_shared.h:1131
	EV_PLAYER_TELEPORT               = 6                                // game/q_shared.h:1131
	EV_OTHER_TELEPORT                = 7                                // game/q_shared.h:1131
	VIDREF_GL                        = 1                                // game/q_shared.h:1194
	VIDREF_SOFT                      = 2                                // game/q_shared.h:1195
	VIDREF_OTHER                     = 3                                // game/q_shared.h:1196
	VERSION                          = 3.19                             // qcommon/qcommon.h:26
	BASEDIRNAME                      = "baseq2"                         // qcommon/qcommon.h:28
	PROTOCOL_VERSION                 = 34                               // qcommon/qcommon.h:180
	PORT_MASTER                      = 27900                            // qcommon/qcommon.h:184
	PORT_CLIENT                      = 27901                            // qcommon/qcommon.h:185
	PORT_SERVER                      = 27910                            // qcommon/qcommon.h:186
	UPDATE_BACKUP                    = 16                               // qcommon/qcommon.h:190
	UPDATE_MASK                      = 15                               // qcommon/qcommon.h:192
	Svc_bad                          = 0                                // qcommon/qcommon.h:230
	Svc_muzzleflash                  = 1                                // qcommon/qcommon.h:230
	Svc_muzzleflash2                 = 2                                // qcommon/qcommon.h:230
	Svc_temp_entity                  = 3                                // qcommon/qcommon.h:230
	Svc_layout                       = 4                                // qcommon/qcommon.h:230
	Svc_inventory                    = 5                                // qcommon/qcommon.h:230
	Svc_nop                          = 6                                // qcommon/qcommon.h:230
	Svc_disconnect                   = 7                                // qcommon/qcommon.h:230
	Svc_reconnect                    = 8                                // qcommon/qcommon.h:230
	Svc_sound                        = 9                                // qcommon/qcommon.h:230
	Svc_print                        = 10                               // qcommon/qcommon.h:230
	Svc_stufftext                    = 11                               // qcommon/qcommon.h:230
	Svc_serverdata                   = 12                               // qcommon/qcommon.h:230
	Svc_configstring                 = 13                               // qcommon/qcommon.h:230
	Svc_spawnbaseline                = 14                               // qcommon/qcommon.h:230
	Svc_centerprint                  = 15                               // qcommon/qcommon.h:230
	Svc_download                     = 16                               // qcommon/qcommon.h:230
	Svc_playerinfo                   = 17                               // qcommon/qcommon.h:230
	Svc_packetentities               = 18                               // qcommon/qcommon.h:230
	Svc_deltapacketentities          = 19                               // qcommon/qcommon.h:230
	Svc_frame                        = 20                               // qcommon/qcommon.h:230
	Clc_bad                          = 0                                // qcommon/qcommon.h:244
	Clc_nop                          = 1                                // qcommon/qcommon.h:244
	Clc_move                         = 2                                // qcommon/qcommon.h:244
	Clc_userinfo                     = 3                                // qcommon/qcommon.h:244
	Clc_stringcmd                    = 4                                // qcommon/qcommon.h:244
	PS_M_TYPE                        = 1                                // qcommon/qcommon.h:250
	PS_M_ORIGIN                      = 2                                // qcommon/qcommon.h:251
	PS_M_VELOCITY                    = 4                                // qcommon/qcommon.h:252
	PS_M_TIME                        = 8                                // qcommon/qcommon.h:253
	PS_M_FLAGS                       = 16                               // qcommon/qcommon.h:254
	PS_M_GRAVITY                     = 32                               // qcommon/qcommon.h:255
	PS_M_DELTA_ANGLES                = 64                               // qcommon/qcommon.h:256
	PS_VIEWOFFSET                    = 128                              // qcommon/qcommon.h:258
	PS_VIEWANGLES                    = 256                              // qcommon/qcommon.h:259
	PS_KICKANGLES                    = 512                              // qcommon/qcommon.h:260
	PS_BLEND                         = 1024                             // qcommon/qcommon.h:261
	PS_FOV                           = 2048                             // qcommon/qcommon.h:262
	PS_WEAPONINDEX                   = 4096                             // qcommon/qcommon.h:263
	PS_WEAPONFRAME                   = 8192                             // qcommon/qcommon.h:264
	PS_RDFLAGS                       = 16384                            // qcommon/qcommon.h:265
	CM_ANGLE1                        = 1                                // qcommon/qcommon.h:272
	CM_ANGLE2                        = 2                                // qcommon/qcommon.h:273
	CM_ANGLE3                        = 4                                // qcommon/qcommon.h:274
	CM_FORWARD                       = 8                                // qcommon/qcommon.h:275
	CM_SIDE                          = 16                               // qcommon/qcommon.h:276
	CM_UP                            = 32                               // qcommon/qcommon.h:277
	CM_BUTTONS                       = 64                               // qcommon/qcommon.h:278
	CM_IMPULSE                       = 128                              // qcommon/qcommon.h:279
	SND_VOLUME                       = 1                                // qcommon/qcommon.h:284
	SND_ATTENUATION                  = 2                                // qcommon/qcommon.h:285
	SND_POS                          = 4                                // qcommon/qcommon.h:286
	SND_ENT                          = 8                                // qcommon/qcommon.h:287
	SND_OFFSET                       = 16                               // qcommon/qcommon.h:288
	DEFAULT_SOUND_PACKET_VOLUME      = 1                                // qcommon/qcommon.h:290
	DEFAULT_SOUND_PACKET_ATTENUATION = 1                                // qcommon/qcommon.h:291
	U_ORIGIN1                        = 1                                // qcommon/qcommon.h:298
	U_ORIGIN2                        = 2                                // qcommon/qcommon.h:299
	U_ANGLE2                         = 4                                // qcommon/qcommon.h:300
	U_ANGLE3                         = 8                                // qcommon/qcommon.h:301
	U_FRAME8                         = 16                               // qcommon/qcommon.h:302
	U_EVENT                          = 32                               // qcommon/qcommon.h:303
	U_REMOVE                         = 64                               // qcommon/qcommon.h:304
	U_MOREBITS1                      = 128                              // qcommon/qcommon.h:305
	U_NUMBER16                       = 256                              // qcommon/qcommon.h:308
	U_ORIGIN3                        = 512                              // qcommon/qcommon.h:309
	U_ANGLE1                         = 1024                             // qcommon/qcommon.h:310
	U_MODEL                          = 2048                             // qcommon/qcommon.h:311
	U_RENDERFX8                      = 4096                             // qcommon/qcommon.h:312
	U_EFFECTS8                       = 16384                            // qcommon/qcommon.h:313
	U_MOREBITS2                      = 32768                            // qcommon/qcommon.h:314
	U_SKIN8                          = 65536                            // qcommon/qcommon.h:317
	U_FRAME16                        = 131072                           // qcommon/qcommon.h:318
	U_RENDERFX16                     = 262144                           // qcommon/qcommon.h:319
	U_EFFECTS16                      = 524288                           // qcommon/qcommon.h:320
	U_MODEL2                         = 1048576                          // qcommon/qcommon.h:321
	U_MODEL3                         = 2097152                          // qcommon/qcommon.h:322
	U_MODEL4                         = 4194304                          // qcommon/qcommon.h:323
	U_MOREBITS3                      = 8388608                          // qcommon/qcommon.h:324
	U_OLDORIGIN                      = 16777216                         // qcommon/qcommon.h:327
	U_SKIN16                         = 33554432                         // qcommon/qcommon.h:328
	U_SOUND                          = 67108864                         // qcommon/qcommon.h:329
	U_SOLID                          = 134217728                        // qcommon/qcommon.h:330
	EXEC_NOW                         = 0                                // qcommon/qcommon.h:355
	EXEC_INSERT                      = 1                                // qcommon/qcommon.h:356
	EXEC_APPEND                      = 2                                // qcommon/qcommon.h:357
	PORT_ANY                         = -1                               // qcommon/qcommon.h:525
	MAX_MSGLEN                       = 1400                             // qcommon/qcommon.h:527
	PACKET_HEADER                    = 10                               // qcommon/qcommon.h:528
	NA_LOOPBACK                      = 0                                // qcommon/qcommon.h:530
	NA_BROADCAST                     = 1                                // qcommon/qcommon.h:530
	NA_IP                            = 2                                // qcommon/qcommon.h:530
	NA_IPX                           = 3                                // qcommon/qcommon.h:530
	NA_BROADCAST_IPX                 = 4                                // qcommon/qcommon.h:530
	NS_CLIENT                        = 0                                // qcommon/qcommon.h:532
	NS_SERVER                        = 1                                // qcommon/qcommon.h:532
	OLD_AVG                          = 0.99                             // qcommon/qcommon.h:561
	MAX_LATENT                       = 32                               // qcommon/qcommon.h:563
	ERR_QUIT                         = 2                                // qcommon/qcommon.h:728
	NUMVERTEXNORMALS                 = 162                              // qcommon/qcommon.h:775
	IDPAKHEADER                      = 1262698832                       // qcommon/qfiles.h:34
	MAX_FILES_IN_PACK                = 4096                             // qcommon/qfiles.h:49
	IDALIASHEADER                    = 844121161                        // qcommon/qfiles.h:86
	ALIAS_VERSION                    = 8                                // qcommon/qfiles.h:87
	MAX_TRIANGLES                    = 4096                             // qcommon/qfiles.h:89
	MAX_VERTS                        = 2048                             // qcommon/qfiles.h:90
	MAX_FRAMES                       = 512                              // qcommon/qfiles.h:91
	MAX_MD2SKINS                     = 32                               // qcommon/qfiles.h:92
	MAX_SKINNAME                     = 64                               // qcommon/qfiles.h:93
	DTRIVERTX_V0                     = 0                                // qcommon/qfiles.h:113
	DTRIVERTX_V1                     = 1                                // qcommon/qfiles.h:114
	DTRIVERTX_V2                     = 2                                // qcommon/qfiles.h:115
	DTRIVERTX_LNI                    = 3                                // qcommon/qfiles.h:116
	DTRIVERTX_SIZE                   = 4                                // qcommon/qfiles.h:117
	IDSPRITEHEADER                   = 844317769                        // qcommon/qfiles.h:170
	SPRITE_VERSION                   = 2                                // qcommon/qfiles.h:172
	MIPLEVELS                        = 4                                // qcommon/qfiles.h:197
	IDBSPHEADER                      = 1347633737                       // qcommon/qfiles.h:219
	BSPVERSION                       = 38                               // qcommon/qfiles.h:222
	MAX_MAP_MODELS                   = 1024                             // qcommon/qfiles.h:228
	MAX_MAP_BRUSHES                  = 8192                             // qcommon/qfiles.h:229
	MAX_MAP_ENTITIES                 = 2048                             // qcommon/qfiles.h:230
	MAX_MAP_ENTSTRING                = 262144                           // qcommon/qfiles.h:231
	MAX_MAP_TEXINFO                  = 8192                             // qcommon/qfiles.h:232
	MAX_MAP_AREAS                    = 256                              // qcommon/qfiles.h:234
	MAX_MAP_AREAPORTALS              = 1024                             // qcommon/qfiles.h:235
	MAX_MAP_PLANES                   = 65536                            // qcommon/qfiles.h:236
	MAX_MAP_NODES                    = 65536                            // qcommon/qfiles.h:237
	MAX_MAP_BRUSHSIDES               = 65536                            // qcommon/qfiles.h:238
	MAX_MAP_LEAFS                    = 65536                            // qcommon/qfiles.h:239
	MAX_MAP_VERTS                    = 65536                            // qcommon/qfiles.h:240
	MAX_MAP_FACES                    = 65536                            // qcommon/qfiles.h:241
	MAX_MAP_LEAFFACES                = 65536                            // qcommon/qfiles.h:242
	MAX_MAP_LEAFBRUSHES              = 65536                            // qcommon/qfiles.h:243
	MAX_MAP_PORTALS                  = 65536                            // qcommon/qfiles.h:244
	MAX_MAP_EDGES                    = 128000                           // qcommon/qfiles.h:245
	MAX_MAP_SURFEDGES                = 256000                           // qcommon/qfiles.h:246
	MAX_MAP_LIGHTING                 = 2097152                          // qcommon/qfiles.h:247
	MAX_MAP_VISIBILITY               = 1048576                          // qcommon/qfiles.h:248
	MAX_KEY                          = 32                               // qcommon/qfiles.h:252
	MAX_VALUE                        = 1024                             // qcommon/qfiles.h:253
	LUMP_ENTITIES                    = 0                                // qcommon/qfiles.h:262
	LUMP_PLANES                      = 1                                // qcommon/qfiles.h:263
	LUMP_VERTEXES                    = 2                                // qcommon/qfiles.h:264
	LUMP_VISIBILITY                  = 3                                // qcommon/qfiles.h:265
	LUMP_NODES                       = 4                                // qcommon/qfiles.h:266
	LUMP_TEXINFO                     = 5                                // qcommon/qfiles.h:267
	LUMP_FACES                       = 6                                // qcommon/qfiles.h:268
	LUMP_LIGHTING                    = 7                                // qcommon/qfiles.h:269
	LUMP_LEAFS                       = 8                                // qcommon/qfiles.h:270
	LUMP_LEAFFACES                   = 9                                // qcommon/qfiles.h:271
	LUMP_LEAFBRUSHES                 = 10                               // qcommon/qfiles.h:272
	LUMP_EDGES                       = 11                               // qcommon/qfiles.h:273
	LUMP_SURFEDGES                   = 12                               // qcommon/qfiles.h:274
	LUMP_MODELS                      = 13                               // qcommon/qfiles.h:275
	LUMP_BRUSHES                     = 14                               // qcommon/qfiles.h:276
	LUMP_BRUSHSIDES                  = 15                               // qcommon/qfiles.h:277
	LUMP_POP                         = 16                               // qcommon/qfiles.h:278
	LUMP_AREAS                       = 17                               // qcommon/qfiles.h:279
	LUMP_AREAPORTALS                 = 18                               // qcommon/qfiles.h:280
	HEADER_LUMPS                     = 19                               // qcommon/qfiles.h:281
	PLANE_X                          = 0                                // qcommon/qfiles.h:307
	PLANE_Y                          = 1                                // qcommon/qfiles.h:308
	PLANE_Z                          = 2                                // qcommon/qfiles.h:309
	PLANE_ANYX                       = 3                                // qcommon/qfiles.h:312
	PLANE_ANYY                       = 4                                // qcommon/qfiles.h:313
	PLANE_ANYZ                       = 5                                // qcommon/qfiles.h:314
	MAXLIGHTMAPS                     = 4                                // qcommon/qfiles.h:409
	ANGLE_UP                         = -1                               // qcommon/qfiles.h:454
	ANGLE_DOWN                       = -2                               // qcommon/qfiles.h:455
	DVIS_PVS                         = 0                                // qcommon/qfiles.h:461
	DVIS_PHS                         = 1                                // qcommon/qfiles.h:462
	GAME_API_VERSION                 = 3                                // game/game.h:42
	SVF_NOCLIENT                     = 1                                // game/game.h:46
	SVF_DEADMONSTER                  = 2                                // game/game.h:47
	SVF_MONSTER                      = 4                                // game/game.h:48
	SOLID_NOT                        = 0                                // game/game.h:58
	SOLID_TRIGGER                    = 1                                // game/game.h:58
	SOLID_BBOX                       = 2                                // game/game.h:58
	SOLID_BSP                        = 3                                // game/game.h:58
	MAX_ENT_CLUSTERS                 = 16                               // game/game.h:68
	K_TAB                            = 9                                // client/keys.h:24
	K_ENTER                          = 13                               // client/keys.h:25
	K_ESCAPE                         = 27                               // client/keys.h:26
	K_SPACE                          = 32                               // client/keys.h:27
	K_BACKSPACE                      = 127                              // client/keys.h:31
	K_UPARROW                        = 128                              // client/keys.h:32
	K_DOWNARROW                      = 129                              // client/keys.h:33
	K_LEFTARROW                      = 130                              // client/keys.h:34
	K_RIGHTARROW                     = 131                              // client/keys.h:35
	K_ALT                            = 132                              // client/keys.h:37
	K_CTRL                           = 133                              // client/keys.h:38
	K_SHIFT                          = 134                              // client/keys.h:39
	K_F1                             = 135                              // client/keys.h:40
	K_F2                             = 136                              // client/keys.h:41
	K_F3                             = 137                              // client/keys.h:42
	K_F4                             = 138                              // client/keys.h:43
	K_F5                             = 139                              // client/keys.h:44
	K_F6                             = 140                              // client/keys.h:45
	K_F7                             = 141                              // client/keys.h:46
	K_F8                             = 142                              // client/keys.h:47
	K_F9                             = 143                              // client/keys.h:48
	K_F10                            = 144                              // client/keys.h:49
	K_F11                            = 145                              // client/keys.h:50
	K_F12                            = 146                              // client/keys.h:51
	K_INS                            = 147                              // client/keys.h:52
	K_DEL                            = 148                              // client/keys.h:53
	K_PGDN                           = 149                              // client/keys.h:54
	K_PGUP                           = 150                              // client/keys.h:55
	K_HOME                           = 151                              // client/keys.h:56
	K_END                            = 152                              // client/keys.h:57
	K_KP_HOME                        = 160                              // client/keys.h:59
	K_KP_UPARROW                     = 161                              // client/keys.h:60
	K_KP_PGUP                        = 162                              // client/keys.h:61
	K_KP_LEFTARROW                   = 163                              // client/keys.h:62
	K_KP_5                           = 164                              // client/keys.h:63
	K_KP_RIGHTARROW                  = 165                              // client/keys.h:64
	K_KP_END                         = 166                              // client/keys.h:65
	K_KP_DOWNARROW                   = 167                              // client/keys.h:66
	K_KP_PGDN                        = 168                              // client/keys.h:67
	K_KP_ENTER                       = 169                              // client/keys.h:68
	K_KP_INS                         = 170                              // client/keys.h:69
	K_KP_DEL                         = 171                              // client/keys.h:70
	K_KP_SLASH                       = 172                              // client/keys.h:71
	K_KP_MINUS                       = 173                              // client/keys.h:72
	K_KP_PLUS                        = 174                              // client/keys.h:73
	K_PAUSE                          = 255                              // client/keys.h:75
	K_MOUSE1                         = 200                              // client/keys.h:80
	K_MOUSE2                         = 201                              // client/keys.h:81
	K_MOUSE3                         = 202                              // client/keys.h:82
	K_JOY1                           = 203                              // client/keys.h:87
	K_JOY2                           = 204                              // client/keys.h:88
	K_JOY3                           = 205                              // client/keys.h:89
	K_JOY4                           = 206                              // client/keys.h:90
	K_AUX1                           = 207                              // client/keys.h:96
	K_AUX2                           = 208                              // client/keys.h:97
	K_AUX3                           = 209                              // client/keys.h:98
	K_AUX4                           = 210                              // client/keys.h:99
	K_AUX5                           = 211                              // client/keys.h:100
	K_AUX6                           = 212                              // client/keys.h:101
	K_AUX7                           = 213                              // client/keys.h:102
	K_AUX8                           = 214                              // client/keys.h:103
	K_AUX9                           = 215                              // client/keys.h:104
	K_AUX10                          = 216                              // client/keys.h:105
	K_AUX11                          = 217                              // client/keys.h:106
	K_AUX12                          = 218                              // client/keys.h:107
	K_AUX13                          = 219                              // client/keys.h:108
	K_AUX14                          = 220                              // client/keys.h:109
	K_AUX15                          = 221                              // client/keys.h:110
	K_AUX16                          = 222                              // client/keys.h:111
	K_AUX17                          = 223                              // client/keys.h:112
	K_AUX18                          = 224                              // client/keys.h:113
	K_AUX19                          = 225                              // client/keys.h:114
	K_AUX20                          = 226                              // client/keys.h:115
	K_AUX21                          = 227                              // client/keys.h:116
	K_AUX22                          = 228                              // client/keys.h:117
	K_AUX23                          = 229                              // client/keys.h:118
	K_AUX24                          = 230                              // client/keys.h:119
	K_AUX25                          = 231                              // client/keys.h:120
	K_AUX26                          = 232                              // client/keys.h:121
	K_AUX27                          = 233                              // client/keys.h:122
	K_AUX28                          = 234                              // client/keys.h:123
	K_AUX29                          = 235                              // client/keys.h:124
	K_AUX30                          = 236                              // client/keys.h:125
	K_AUX31                          = 237                              // client/keys.h:126
	K_AUX32                          = 238                              // client/keys.h:127
	K_MWHEELDOWN                     = 239                              // client/keys.h:129
	K_MWHEELUP                       = 240                              // client/keys.h:130
	MAX_DLIGHTS                      = 32                               // client/ref.h:23
	MAX_ENTITIES                     = 128                              // client/ref.h:24
	MAX_PARTICLES                    = 4096                             // client/ref.h:25
	POWERSUIT_SCALE                  = 4                                // client/ref.h:28
	SHELL_RED_COLOR                  = 242                              // client/ref.h:30
	SHELL_GREEN_COLOR                = 208                              // client/ref.h:31
	SHELL_BLUE_COLOR                 = 243                              // client/ref.h:32
	SHELL_RG_COLOR                   = 220                              // client/ref.h:34
	SHELL_RB_COLOR                   = 104                              // client/ref.h:36
	SHELL_BG_COLOR                   = 120                              // client/ref.h:37
	SHELL_DOUBLE_COLOR               = 223                              // client/ref.h:40
	SHELL_HALF_DAM_COLOR             = 144                              // client/ref.h:41
	SHELL_CYAN_COLOR                 = 114                              // client/ref.h:42
	SHELL_WHITE_COLOR                = 215                              // client/ref.h:45
	ENTITY_FLAGS                     = 68                               // client/ref.h:78
	API_VERSION                      = 3                                // client/ref.h:126
	MAX_CLIENTWEAPONMODELS           = 20                               // client/client.h:68
	CMD_BACKUP                       = 64                               // client/client.h:84
	MAX_PARSE_ENTITIES               = 1024                             // client/client.h:311
	MAX_MASTERS                      = 8                                // server/server.h:30
	LATENCY_COUNTS                   = 16                               // server/server.h:92
	RATE_MESSAGES                    = 10                               // server/server.h:93
)

// ByteDirs is the 162-entry normal table (client/anorms.h), used by MSG_WriteDir/ReadDir and MD2 normals.
var ByteDirs = [162][3]float32{
	{-0.525731, 0, 0.850651},
	{-0.442863, 0.238856, 0.864188},
	{-0.295242, 0, 0.955423},
	{-0.309017, 0.5, 0.809017},
	{-0.16246, 0.262866, 0.951056},
	{0, 0, 1},
	{0, 0.850651, 0.525731},
	{-0.147621, 0.716567, 0.681718},
	{0.147621, 0.716567, 0.681718},
	{0, 0.525731, 0.850651},
	{0.309017, 0.5, 0.809017},
	{0.525731, 0, 0.850651},
	{0.295242, 0, 0.955423},
	{0.442863, 0.238856, 0.864188},
	{0.16246, 0.262866, 0.951056},
	{-0.681718, 0.147621, 0.716567},
	{-0.809017, 0.309017, 0.5},
	{-0.587785, 0.425325, 0.688191},
	{-0.850651, 0.525731, 0},
	{-0.864188, 0.442863, 0.238856},
	{-0.716567, 0.681718, 0.147621},
	{-0.688191, 0.587785, 0.425325},
	{-0.5, 0.809017, 0.309017},
	{-0.238856, 0.864188, 0.442863},
	{-0.425325, 0.688191, 0.587785},
	{-0.716567, 0.681718, -0.147621},
	{-0.5, 0.809017, -0.309017},
	{-0.525731, 0.850651, 0},
	{0, 0.850651, -0.525731},
	{-0.238856, 0.864188, -0.442863},
	{0, 0.955423, -0.295242},
	{-0.262866, 0.951056, -0.16246},
	{0, 1, 0},
	{0, 0.955423, 0.295242},
	{-0.262866, 0.951056, 0.16246},
	{0.238856, 0.864188, 0.442863},
	{0.262866, 0.951056, 0.16246},
	{0.5, 0.809017, 0.309017},
	{0.238856, 0.864188, -0.442863},
	{0.262866, 0.951056, -0.16246},
	{0.5, 0.809017, -0.309017},
	{0.850651, 0.525731, 0},
	{0.716567, 0.681718, 0.147621},
	{0.716567, 0.681718, -0.147621},
	{0.525731, 0.850651, 0},
	{0.425325, 0.688191, 0.587785},
	{0.864188, 0.442863, 0.238856},
	{0.688191, 0.587785, 0.425325},
	{0.809017, 0.309017, 0.5},
	{0.681718, 0.147621, 0.716567},
	{0.587785, 0.425325, 0.688191},
	{0.955423, 0.295242, 0},
	{1, 0, 0},
	{0.951056, 0.16246, 0.262866},
	{0.850651, -0.525731, 0},
	{0.955423, -0.295242, 0},
	{0.864188, -0.442863, 0.238856},
	{0.951056, -0.16246, 0.262866},
	{0.809017, -0.309017, 0.5},
	{0.681718, -0.147621, 0.716567},
	{0.850651, 0, 0.525731},
	{0.864188, 0.442863, -0.238856},
	{0.809017, 0.309017, -0.5},
	{0.951056, 0.16246, -0.262866},
	{0.525731, 0, -0.850651},
	{0.681718, 0.147621, -0.716567},
	{0.681718, -0.147621, -0.716567},
	{0.850651, 0, -0.525731},
	{0.809017, -0.309017, -0.5},
	{0.864188, -0.442863, -0.238856},
	{0.951056, -0.16246, -0.262866},
	{0.147621, 0.716567, -0.681718},
	{0.309017, 0.5, -0.809017},
	{0.425325, 0.688191, -0.587785},
	{0.442863, 0.238856, -0.864188},
	{0.587785, 0.425325, -0.688191},
	{0.688191, 0.587785, -0.425325},
	{-0.147621, 0.716567, -0.681718},
	{-0.309017, 0.5, -0.809017},
	{0, 0.525731, -0.850651},
	{-0.525731, 0, -0.850651},
	{-0.442863, 0.238856, -0.864188},
	{-0.295242, 0, -0.955423},
	{-0.16246, 0.262866, -0.951056},
	{0, 0, -1},
	{0.295242, 0, -0.955423},
	{0.16246, 0.262866, -0.951056},
	{-0.442863, -0.238856, -0.864188},
	{-0.309017, -0.5, -0.809017},
	{-0.16246, -0.262866, -0.951056},
	{0, -0.850651, -0.525731},
	{-0.147621, -0.716567, -0.681718},
	{0.147621, -0.716567, -0.681718},
	{0, -0.525731, -0.850651},
	{0.309017, -0.5, -0.809017},
	{0.442863, -0.238856, -0.864188},
	{0.16246, -0.262866, -0.951056},
	{0.238856, -0.864188, -0.442863},
	{0.5, -0.809017, -0.309017},
	{0.425325, -0.688191, -0.587785},
	{0.716567, -0.681718, -0.147621},
	{0.688191, -0.587785, -0.425325},
	{0.587785, -0.425325, -0.688191},
	{0, -0.955423, -0.295242},
	{0, -1, 0},
	{0.262866, -0.951056, -0.16246},
	{0, -0.850651, 0.525731},
	{0, -0.955423, 0.295242},
	{0.238856, -0.864188, 0.442863},
	{0.262866, -0.951056, 0.16246},
	{0.5, -0.809017, 0.309017},
	{0.716567, -0.681718, 0.147621},
	{0.525731, -0.850651, 0},
	{-0.238856, -0.864188, -0.442863},
	{-0.5, -0.809017, -0.309017},
	{-0.262866, -0.951056, -0.16246},
	{-0.850651, -0.525731, 0},
	{-0.716567, -0.681718, -0.147621},
	{-0.716567, -0.681718, 0.147621},
	{-0.525731, -0.850651, 0},
	{-0.5, -0.809017, 0.309017},
	{-0.238856, -0.864188, 0.442863},
	{-0.262866, -0.951056, 0.16246},
	{-0.864188, -0.442863, 0.238856},
	{-0.809017, -0.309017, 0.5},
	{-0.688191, -0.587785, 0.425325},
	{-0.681718, -0.147621, 0.716567},
	{-0.442863, -0.238856, 0.864188},
	{-0.587785, -0.425325, 0.688191},
	{-0.309017, -0.5, 0.809017},
	{-0.147621, -0.716567, 0.681718},
	{-0.425325, -0.688191, 0.587785},
	{-0.16246, -0.262866, 0.951056},
	{0.442863, -0.238856, 0.864188},
	{0.16246, -0.262866, 0.951056},
	{0.309017, -0.5, 0.809017},
	{0.147621, -0.716567, 0.681718},
	{0, -0.525731, 0.850651},
	{0.425325, -0.688191, 0.587785},
	{0.587785, -0.425325, 0.688191},
	{0.688191, -0.587785, 0.425325},
	{-0.955423, 0.295242, 0},
	{-0.951056, 0.16246, 0.262866},
	{-1, 0, 0},
	{-0.850651, 0, 0.525731},
	{-0.955423, -0.295242, 0},
	{-0.951056, -0.16246, 0.262866},
	{-0.864188, 0.442863, -0.238856},
	{-0.951056, 0.16246, -0.262866},
	{-0.809017, 0.309017, -0.5},
	{-0.864188, -0.442863, -0.238856},
	{-0.951056, -0.16246, -0.262866},
	{-0.809017, -0.309017, -0.5},
	{-0.681718, 0.147621, -0.716567},
	{-0.681718, -0.147621, -0.716567},
	{-0.850651, 0, -0.525731},
	{-0.688191, 0.587785, -0.425325},
	{-0.587785, 0.425325, -0.688191},
	{-0.425325, 0.688191, -0.587785},
	{-0.425325, -0.688191, -0.587785},
	{-0.587785, -0.425325, -0.688191},
	{-0.688191, -0.587785, -0.425325},
}

// MonsterFlashOffset is game/m_flash.c monster_flash_offset, indexed by MZ2_*.
var MonsterFlashOffset = [212][3]float32{
	{0, 0, 0},
	{20.7, -18.5, 28.7},
	{16.6, -21.5, 30.1},
	{11.8, -23.9, 32.1},
	{22.9, -0.7, 25.3},
	{22.2, 6.2, 22.3},
	{19.4, 13.1, 18.6},
	{19.4, 18.8, 18.6},
	{17.9, 25, 18.6},
	{14.1, 30.5, 20.6},
	{9.3, 35.3, 22.1},
	{4.7, 38.4, 22.1},
	{-1.1, 40.4, 24.1},
	{-6.5, 41.2, 24.1},
	{3.2, 40.1, 24.7},
	{11.7, 36.7, 26},
	{18.9, 31.3, 26},
	{24.4, 24.4, 26.4},
	{27.1, 17.1, 27.2},
	{28.5, 9.1, 28},
	{27.1, 2.2, 28},
	{24.9, -2.8, 28},
	{21.6, -7, 26.4},
	{6.2, 29.1, 49.1},
	{6.9, 23.8, 49.1},
	{8.3, 17.8, 49.5},
	{26.6, 7.1, 13.1},
	{18.2, 7.5, 15.4},
	{17.2, 10.3, 17.9},
	{17, 12.8, 20.1},
	{15.1, 14.1, 21.8},
	{11.8, 17.2, 23.1},
	{11.4, 20.2, 21},
	{9, 23, 18.9},
	{13.9, 18.6, 17.7},
	{15.4, 15.6, 15.8},
	{10.2, 15.2, 25.1},
	{-1.9, 15.1, 28.2},
	{-12.4, 13, 20.2},
	{12.72, 9.24, 9.36},
	{25.32, 4.32, 22.8},
	{12.72, 9.24, 9.36},
	{25.32, 4.32, 22.8},
	{12.72, 9.24, 9.36},
	{25.32, 4.32, 22.8},
	{34.615, 4.485, 22.54},
	{33.465, 2.875, 23.805},
	{32.43, 2.875, 25.53},
	{32.43, 4.14, 25.3},
	{30.935, 2.3, 26.91},
	{30.475, 0.69, 23.92},
	{30.935, 0.575, 24.725},
	{33.35, 2.76, 22.425},
	{5.29, -19.32, 8.395},
	{5.29, -19.32, 8.395},
	{5.29, -19.32, 8.395},
	{5.29, -19.32, 8.395},
	{24.8, -9, 39},
	{12.1, 13.4, -14.5},
	{12.1, -7.4, -14.5},
	{12.1, 5.4, 16.5},
	{30, 18, 28},
	{32.5, -0.8, 10},
	{18.4, 7.4, 9.6},
	{30, 30, 88.5},
	{30, 30, 88.5},
	{30, 30, 88.5},
	{30, 30, 88.5},
	{30, 30, 88.5},
	{30, 30, 88.5},
	{16, -22.5, 91.2},
	{16, -33.4, 86.7},
	{16, -42.8, 83.3},
	{32, -40, 70},
	{32, -40, 70},
	{32, -40, 70},
	{32, -40, 70},
	{32, -40, 70},
	{22, 16, 10},
	{22, 8, 10},
	{22, -8, 10},
	{22, -16, 10},
	{32.5, -0.8, 10},
	{24.96, 12.12, -3.24},
	{24.96, 12.12, -3.24},
	{24.96, 12.12, -3.24},
	{9.12, 11.16, 0.96},
	{9.12, 11.16, 0.96},
	{9.12, 11.16, 0.96},
	{36.6, 11.88, -22.44},
	{36.6, 11.88, -22.44},
	{36.6, 11.88, -22.44},
	{33.12, 4.08, -12.48},
	{33.12, 4.08, -12.48},
	{33.12, 4.08, -12.48},
	{34.68, 5.52, -9.72},
	{34.68, 5.52, -9.72},
	{34.68, 5.52, -9.72},
	{37.8, 11.52, 12.12},
	{41.4, 11.52, 7.32},
	{41.4, 11.52, 7.32},
	{17, -19.5, 62.9},
	{-3.6, -24.1, 59.5},
	{-1.6, -19.3, 59.5},
	{-0.1, -14.4, 59.5},
	{2, -7.6, 59.5},
	{3.4, 1.3, 59.5},
	{3.7, 11.1, 59.5},
	{-0.3, 22.3, 59.5},
	{-6, 33, 59.5},
	{-9.3, 36.4, 59.5},
	{-7, 35, 59.5},
	{-2.1, 29, 59.5},
	{3.9, 17.3, 59.5},
	{6.1, 5.8, 59.5},
	{5.9, -4.4, 59.5},
	{4.2, -14.1, 59.5},
	{2.4, -18.8, 59.5},
	{-1.8, -25.5, 59.5},
	{-17.3, 7.8, 72.4},
	{78.5, -47.1, 96},
	{78.5, -47.1, 96},
	{78.5, -47.1, 96},
	{78.5, -47.1, 96},
	{78.5, -47.1, 96},
	{78.5, -47.1, 96},
	{78.5, 46.7, 96},
	{78.5, 46.7, 96},
	{78.5, 46.7, 96},
	{78.5, 46.7, 96},
	{78.5, 46.7, 96},
	{78.5, 46.7, 96},
	{6.3, -9, 111.2},
	{32, 40, 70},
	{32, 40, 70},
	{32, 40, 70},
	{32, 40, 70},
	{32, 40, 70},
	{56, -32, 32},
	{56, 32, 32},
	{42, 24, 50},
	{16, 0, 0},
	{16, 0, 0},
	{16, 0, 0},
	{24, 0, 6},
	{32.5, -0.8, 10},
	{12.1, 5.4, 16.5},
	{32, 0, 6},
	{57.72, 14.5, 88.81},
	{56, 32, 32},
	{62, -20, 84},
	{32, 0, 6},
	{61, -32, 12},
	{61, 32, 12},
	{17, -62, 91},
	{68, 12, 86},
	{47.5, 56, 89},
	{54, 52, 91},
	{58, 40, 91},
	{68, 30, 88},
	{74, 20, 88},
	{73, 11, 87},
	{73, 3, 87},
	{70, -12, 87},
	{67, -20, 90},
	{-20, 76, 90},
	{-8, 74, 90},
	{0, 72, 90},
	{10, 71, 89},
	{23, 70, 87},
	{32, 64, 85},
	{40, 58, 84},
	{48, 50, 83},
	{54, 42, 82},
	{56, 34, 82},
	{58, 26, 82},
	{60, 16, 82},
	{59, 6, 81},
	{58, -2, 80},
	{57, -10, 79},
	{54, -18, 78},
	{42, -32, 80},
	{36, -40, 78},
	{68.4, 10.88, 82.08},
	{68.51, 8.64, 85.14},
	{68.66, 6.38, 88.78},
	{68.73, 5.1, 84.47},
	{68.82, 4.79, 80.52},
	{68.77, 6.11, 85.37},
	{68.67, 7.99, 90.24},
	{68.55, 9.54, 87.36},
	{0, 0, -5},
	{0, 0, -5},
	{0, 0, -5},
	{0, 0, -5},
	{69, -17.63, 93.77},
	{69, -17.08, 89.82},
	{69, -18.4, 90.7},
	{69, -18.34, 94.32},
	{69, -18.3, 97.98},
	{45.04, -59.02, 92.24},
	{50.68, -54.7, 91.96},
	{56.57, -47.72, 91.65},
	{61.75, -38.75, 91.38},
	{65.55, -28.76, 91.24},
	{67.79, -18.9, 91.22},
	{68.6, -9.52, 91.23},
	{68.08, 0.18, 91.32},
	{66.14, 9.79, 91.44},
	{62.77, 18.91, 91.65},
	{58.29, 27.11, 92},
	{0, 0, 0},
}
